[theme]

primaryColor = "#7f5af0"                  # Roxo claro para destaques e botões
backgroundColor = "#16161a"               # Fundo principal bem escuro
secondaryBackgroundColor = "#242629"      # Fundo de cards, containers e sidebar
textColor = "#fffffe"                     # Texto principal branco
font = "sans serif"

successColor = "#2cb67d"                  # Verde para sucesso
warningColor = "#ff8906"                  # Laranja para alertas
infoColor = "#3b82f6"                     # Azul para informações
dangerColor = "#ff3864"                   # Vermelho para erros
